<Project>
	<PropertyGroup>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>

		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
		
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<NoWarn>$(NoWarn);CS1573;CS1591;CS1712</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference
			Include="NewStyleCop.Analyzers"
			Version="1.2.1"
			PrivateAssets="all"
			IncludeAssets="runtime; build; native; contentfiles; analyzers; buildtransitive" />
	</ItemGroup>
</Project>